# syntax = docker/dockerfile:1.2
# Dependency image
FROM node:18.18.0-alpine3.18 AS deps

WORKDIR /usr/src/app

COPY . .

RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn yarn install --frozen-lockfile