services:
  api:
    container_name: steal_manga_api
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    env_file:
      - ./api/.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  web:
    container_name: steal_manga_web
    build:
      context: .
      dockerfile: ./web/Dockerfile.dev
      target: runner
    env_file:
      - ./web/.env
    environment:
      NODE_ENV: development
    command: yarn dev
    ports:
      - "8001:3000"
    volumes:
      - ./web:/app
      - ./web/node_modules:/app/node_modules
      - ./web/.next:/app/.next