version: '3.5'
networks:
  default:
    external:
      name: dev-services_default

services:
  # api:
  #   container_name: steal_manga_api
  #   build:
  #     context: .
  #     dockerfile: ./api/Dockerfile.dev
  #   env_file:
  #     - ./api/.env
  #   environment:
  #     - PORT=8000
  #   command: python manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - '8000:8000'
  #   volumes:
  #     - ./api:/usr/src/app:delegated
  #     - ./api/config:/usr/src/app/config

  # web2:
  #   container_name: steal_manga_web2
  #   build:
  #     context: .
  #     dockerfile: ./web/Dockerfile.dev
  #   env_file:
  #     - ./web/.env
  #   environment:
  #     NODE_ENV: development
  #   command: yarn dev
  #   ports:
  #     - '8002:3000'
  #   volumes:
  #     - ./web:/app:delegated

  api:
    container_name: steal_manga_api
    image: docker.io/acelectic/steal-manga:api
    restart: always
    env_file:
      - ./api/.env
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
    volumes:
      - ./api:/usr/src/app:delegated
      # - ./api/config:/usr/src/app/config

  web:
    container_name: steal_manga_web
    image: docker.io/acelectic/steal-manga:web
    restart: always
    env_file:
      - ./web/.env
    ports:
      - '8001:3000'

  # api_nestjs:
  #   container_name: steal_manga_api_nestjs
  #   image: docker.io/acelectic/steal-manga:api-nestjs
  #   env_file:
  #     - ./api-nestjs/.env
  #   ports:
  #     - 8003:3000
  #   volumes:
  #     - ./api-nestjs/private:/usr/src/app/private
  #     - ./api-nestjs/public:/usr/src/app/public

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    restart: always
    command:
      - 'start'
      - '--all'
      - '--config'
      - '/etc/ngrok.yml'
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - web
      - api
