services:
  api:
    container_name: steal_manga_api
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    env_file:
      - ./api/.env
    environment:
      - PORT=8000
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./api:/usr/src/app:delegated
      - ./api/config:/usr/src/app/config
  web:
    container_name: steal_manga_web
    build:
      context: .
      dockerfile: ./web/Dockerfile.dev
      target: runner
    env_file:
      - ./web/.env
    environment:
      NODE_ENV: development
    command: yarn dev
    ports:
      - '8001:3000'
    volumes:
      - ./web:/app:delegated
      - ./web/.next:/app/.next
