env:
  GH_TOKEN: 'xxx'
  UPDATE_MINUTE_THRESHOLD: '2'
  DRIVE_CARTOONS_DIR_ID: '1iXUAF2N3YxLPvJyDTYYL1f8HFP1mU1Ek'
  DELETE_FILE_AFTER_UPLOADED: 'true'
  APP_URL: 'http://localhost:8000'
  WEB_URL: 'http://localhost:8001'
  GOOGLE_AUTH_TYPE: 'installed'
  GOOGLE_CLIENT_ID: '659780385979-k3f1i7ran018p7qp1eiper859ru0etmr.apps.googleusercontent.com'
  GOOGLE_PROJECT_ID: 'mange-steal'
  GOOGLE_CLIENT_SECRET: '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'
  GOOGLE_REDIRECT_URIS: 'http://localhost'

resources:
  limits:
    cpu: '250m'
    memory: '384Mi'
  requests:
    cpu: '50m'
    memory: '128Mi'

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 300
