export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return <section style={{ padding: '20px' }}>{children}</section>
}
