import { ReactQueryProvider } from '../components/providers/ReactQueryProvider'
import { AppProvider } from '../components/providers/AppProvider'
import EmotionProvider from '../components/providers/EmotionProvider'
import './globals.css'
import { Sarabun } from 'next/font/google'
import React from 'react'
import { AntdProvider } from '../components/providers/AntdProvider'

const inter = Sarabun({ weight: '400', subsets: ['thai'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundColor: '#80bcdf',
          width: '100vw',
          height: '100vh',
        }}
      >
        <AntdProvider>
          <EmotionProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </EmotionProvider>
        </AntdProvider>
      </body>
    </html>
  )
}
