import ReactQueryProvider from '../components/providers/ReactQueryProvider'
import EmotionProvider from '../components/providers/EmotionProvider'
import './globals.css'
import { Sarabun } from 'next/font/google'
import React from 'react'
import AntdProvider from '../components/providers/AntdProvider'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import Navbar from '../components/layouts/Navbar'
import AppLayout from '../components/layouts/index.'

const inter = Sarabun({ weight: '400', subsets: ['thai'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdProvider>
          <EmotionProvider>
            <ReactQueryProvider>
              <AppLayout>{children}</AppLayout>
            </ReactQueryProvider>
          </EmotionProvider>
        </AntdProvider>
      </body>
    </html>
  )
}
