apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-service.fullname" . }}-configmap
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{ toYaml .Values.env | indent 2 }}