FROM python:3.11.4-slim AS builder

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils \
    && apt-get -y install curl \
    && apt-get install libgomp1

COPY api/requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip pip install pip --upgrade \
    && pip install --user -r requirements.txt

FROM python:3.11.4-slim AS production

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ARG PORT
WORKDIR /usr/src/app

RUN apt-get update \
    && apt-get install -y wget

# Default powerline10k theme, no plugins installed 
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)"

COPY --from=builder /root/.local /root/.local
COPY ./api .

ENV PORT=$PORT

RUN mkdir -p /usr/scr/app/staticfiles

EXPOSE $PORT