name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    # - name: Python Semantic Release
    #   uses: relekang/python-semantic-release@master
    #   with:
    #     github_token: ${{ secrets.GH_TOKEN }}
    #     repository_username: ${{ secrets.GH_USERNAME }}
    #     repository_password: ${{ secrets.GH_PASSWORD }}
    #   env:
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Python Semantic Release 2
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        echo $GH_TOKEN
        semantic-release publish -D commit_author="github-actions <action@github.com>"
      env:
        GH_TOKEN: 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
