FROM node:20.6.0-alpine3.18 AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY ./web/package.json ./web/yarn.lock ./
RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn yarn --frozen-lockfile

FROM node:20.6.0-alpine3.18 AS runner
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package.json ./package.json

COPY ./web/. .

EXPOSE 3000

ENV PORT 3000