FROM node:20.6.0-alpine3.18 AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY ./package.json ./yarn.lock ./
RUN yarn --frozen-lockfile

FROM node:20.6.0-alpine3.18 AS runner
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package.json ./package.json

COPY . .

EXPOSE 3000

ENV PORT 3000