FROM node:18-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY ./web/package.json ./web/yarn.lock ./
RUN yarn --frozen-lockfile

FROM node:18-alpine AS runner
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package.json ./package.json

COPY . .

EXPOSE 3000

ENV PORT 3000